package eu.kiaru.ij.controller42.stdDevices;

import java.io.File;

import eu.kiaru.ij.controller42.structDevice.DefaultSynchronizedDisplayedDevice;

public class StdDeviceFactory {
	public static boolean isTiffFile(File path) {
		return path.getPath().toLowerCase().endsWith(".tiff"); 
	}
	
	public static DefaultSynchronizedDisplayedDevice getDevice(File path) {
		DefaultSynchronizedDisplayedDevice myDevice=null;		
		System.out.println("on y va avec"+path.getName());
		if (isTiffFile(path)) {
			// Log file
			// Is it a device generated by the Matlab Controller42 app ?
			/*
			myDevice = Device42Helper.getController42Device(path);
			if (myDevice!=null) {
				System.out.println(path.getAbsolutePath()+" ok!");
				return myDevice;
			} else {

				System.out.println(path.getAbsolutePath()+" not ok :-(");
			}*/
			System.out.println(path.getName()+" is tiff, but what the fuck!");
			myDevice = new ImagePlusDeviceUniformlySampled();
			myDevice.initDevice(path, 0);
			System.out.println("normally initialized...");
			return myDevice;
			
		}	else {
			System.out.println(path.getName()+" is not tiff!");
			
		}
		return null;
	}
}
