Interface is made via java/matlab/micromanager

infos on this link

http://valelab.ucsf.edu/~MM/MMwiki/index.php/Matlab_Configuration

    Installing micromanager version 1.4.5 64 bits to C:\Micro-Manager-1.4 (no space in the directory)
    Going to control panel > system > advanced system settings > environment variables
    make a new 'User variable for Dr Roux named 'PATH' and set it to the location of Micro-Manager ( C:/Micro-Manager-1.4). 

    launch matlab edit classpath.txt, added at the beginning : 

C:/Micro-Manager-1.4/ij.jar C:/Micro-Manager-1.4/plugins/Micro-Manager/MMCoreJ.jar C:/Micro-Manager-1.4/plugins/Micro-Manager/MMJ_.jar C:/Micro-Manager-1.4/plugins/Micro-Manager/bsh-2.0b4.jar C:/Micro-Manager-1.4/plugins/Micro-Manager/swingx-0.9.5.jar

    >> edit librarypath.txt
        added C:\Micro-Manager-1.4 

Matlab works only if the PATH variable is set, but micromanager works only if it is not set.

Nikon_ZDrive.cfg

    # Generated by Configurator on Wed Jul 06 16:18:47 CEST 2011
    # Reset
    Property,Core,Initialize,0
    # Devices
    Device,TIScope,NikonTI,TIScope
    Device,TIZDrive,NikonTI,TIZDrive
    # Pre-init settings for devices
    # Pre-init settings for COM ports
    # Initialize
    Property,Core,Initialize,1
    # Delays
    # Roles
    Property,Core,Focus,TIZDrive
    Property,Core,AutoShutter,1
    # Camera-synchronized devices
    # Labels
    # Configuration presets
    # Group: Channel
    # Group: System
    # Preset: Startup
    # PixelSize settings

Matlab command example

>> import mmcorej.*;
>> mmc=CMMCore;
>> mmc.loadSystemConfiguration ('C:\Micro-Manager-1.4\Nikon_ZDrive.cfg');
>> currz=mmc.getPosition('TIZDrive')
>> mmc.setPosition('TIZDrive',504); 


% import mmcorej.*;
% mmc=CMMCore;
% mmc.loadSystemConfiguration ('C:\Micro-Manager\Nikon_ZDrive.cfg');
% currz=handles.mmc.getPosition('TIZDrive');
% handles.mmc.setPosition('TIZDrive',z);
import mmcorej.*;
mmc.loadSystemConfiguration ('C:\Micro-Manager-1.4\Nikon_ZDrive.cfg');
mmc=CMMCore;
mmc.loadSystemConfiguration ('C:\Micro-Manager-1.4\Nikon_ZDrive.cfg');
currz=mmc.getPosition('TIZDrive');
currz
mmc.setPosition('TIZDrive',currz+1);
currz=mmc.getPosition('TIZDrive');mmc.setPosition('TIZDrive',currz+1);
currz=mmc.getPosition('TIZDrive');mmc.setPosition('TIZDrive',currz-50);
currz=mmc.getPosition('TIZDrive');mmc.setPosition('TIZDrive',currz+1);
currz=mmc.getPosition('TIZDrive');mmc.setPosition('TIZDrive',currz-1);
currz=mmc.getPosition('TIZDrive');mmc.setPosition('TIZDrive',currz-0.1);
currz=mmc.getPosition('TIZDrive');mmc.setPosition('TIZDrive',currz+0.3);
currz=mmc.getPosition('TIZDrive');mmc.setPosition('TIZDrive',currz+0.2);
currz=mmc.getPosition('TIZDrive');mmc.setPosition('TIZDrive',currz-0.2);
currz=mmc.getPosition('TIZDrive');mmc.setPosition('TIZDrive',currz+0.2);
import mmcorej.*;
mmc.loadSystemConfiguration ('C:\Micro-Manager-1.4\MMConfig_demo.cfg');
mmc=CMMCore;
mmc.loadSystemConfiguration ('C:\Micro-Manager-1.4\MMConfig_demo.cfg');
%-- 7/6/2011 4:25 PM --%
import mmcorej.*;
mmc=CMMCore;
mmc.loadSystemConfiguration ('C:\Micro-Manager-1.4\MMConfig_demo.cfg');
mmc.loadSystemConfiguration ('C:\Micro-Manager-1.4\Nikon_ZDrive.cfg');
currz=mmc.getPosition('TIZDrive');
currz
mmc.setPosition('TIZDrive',505);
%-- 7/6/2011 4:39 PM --%
import mmcorej.*;
mmc=CMMCore;
mmc.loadSystemConfiguration ('C:\Micro-Manager-1.4\Nikon_ZDrive.cfg');
currz=mmc.getPosition('TIZDrive');
currz=mmc.getPosition('TIZDrive')
mmc.setPosition('TIZDrive',504);
import mmcorej.*;
mmc=CMMCore;
mmc.loadSystemConfiguration ('C:\Micro-Manager-1.4\MMConfig_demo.cfg');
mmc.snapImage();
img=mmc.getImage();
width=mmc.getImageWidth();
height=mmc.getImageHeight();
img2=typecast(img,'uint8');
img2=reshape(img2,[height,width]);
imshow(img2);

edit classpath.txt
C:/Micro-Manager/ij.jar
C:/Micro-Manager/plugins/Micro-Manager/MMCoreJ.jar
C:/Micro-Manager/plugins/Micro-Manager/MMJ_.jar
C:/Micro-Manager/plugins/Micro-Manager/bsh-2.0b4.jar
C:/Micro-Manager/plugins/Micro-Manager/swingx-0.9.5.jar

function setdynpath
javaclasspath({
   'C:\Work\Java\ClassFiles', ...
   'C:\Work\JavaTest\curvefit.jar', ...
   'C:\Work\JavaTest\timer.jar', ...
   'C:\Work\JavaTest\patch.jar'});
% end of file 
javaclasspath({
    'C:/Micro-Manager/ij.jar', ...
    'C:/Micro-Manager/plugins/Micro-Manager/MMCoreJ.jar', ...
    'C:/Micro-Manager/plugins/Micro-Manager/MMJ_.jar', ...
    'C:/Micro-Manager/plugins/Micro-Manager/bsh-2.0b4.jar', ...
    'C:/Micro-Manager/plugins/Micro-Manager/swingx-0.9.5.jar'});



edit librarypath.txt
C:\Micro-Manager
