package eu.kiaru.ij.controller42.devices;

import java.io.File;
import java.util.Map;

import eu.kiaru.ij.controller42.DefaultSynchronizedDisplayedDevice;

public class DeviceFactory {
	
	public static DefaultSynchronizedDisplayedDevice getDevice(File path) {
		DefaultSynchronizedDisplayedDevice myDevice=null;		
		if (isLogFile(path)) {
			// Log file
			// Is it a device generated by the Matlab Controller42 app ?
			myDevice = Controller42Device.getController42Device(path);
			if (myDevice!=null) {
				System.out.println(path.getAbsolutePath()+" ok!");
				return myDevice;
			} else {

				System.out.println(path.getAbsolutePath()+" not ok :-(");
			}
			
		}	
		return null;
	}
	
	public static boolean isLogFile(File path) {
		return path.getPath().toLowerCase().endsWith(".log"); 
	}
	
	public static void linkDevices(Map<String,DefaultSynchronizedDisplayedDevice> devices) {
		for (DefaultSynchronizedDisplayedDevice device: devices.values()) {
			if (device.getClass()==CamTrackerDevice.class) {
				((CamTrackerDevice)device).setLinkedCamera((CameraDevice)(devices.get(((CamTrackerDevice)device).linkedCamName)));
			}
		}
		// not clean
		/*if ((CameraDevice)devices.get("CAMERA_GUPPY")!=null)
			((CamTrackerDevice) devices.get("BEAD_TRACKER")).setLinkedCamera((CameraDevice)devices.get("CAMERA_GUPPY"));*/
	}
	

	
}
